version: '3.2'
services:
  spy_data:
    ports:
      - "2222:22"
  spy_db:
    ports:
      - 5432:5432
  spy_redis:
    ports:
      - 6379:6379
  spy_elasticsearch:
    ports:
      - 9200:9200
  spy_rabbitmq:
    ports:
      - 15672:15672
  spy_jenkins:
    ports:
      - 8080:8080
  spy_loadbalancer:
    ports:
     - "80:80"
  spy_mailcatcher:
   image: schickling/mailcatcher
   container_name: spy_mailcatcher
   ports:
     - 1080:1080
  spy_redisui:
    image: tenstartups/redis-commander
    container_name: spy_redisui
    command: --redis-host redis
    links:
      - spy_redis:redis
    ports:
      - "8081:8081"