version: '3.2'
services:
  spy_data:
    build: ./env/ssh
    container_name: spy_data
    image: spryker_data
    volumes:
      - spy_projectdata:/data/shop/development
    environment:
      APPLICATION_ENV: development
  spy_php:
    container_name: spy_php
    image: nexusnetsoft/spryker-php-fpm:7.3
    env_file:
      - ./env/php.env
    volumes:
      - spy_projectdata:/data/shop/development
    depends_on:
      - spy_data
  spy_db:
    image: postgres:9.6.10
    container_name: spy_db
    env_file:
      - ./env/db.env
    volumes:
      - spy_dbdata:/var/lib/postgresql/data
  spy_redis:
    image: redis:3.2.11
    container_name: spy_redis
    command: redis-server --appendonly yes
    volumes:
      - spy_redisdata:/data
  spy_elasticsearch:
    image: elasticsearch:5.6.8
    container_name: spy_elasticsearch
    volumes:
      - ./env/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - spy_elasticdata:/usr/share/elasticsearch/data
  spy_rabbitmq:
    image: rabbitmq:3.7.3-management
    container_name: spy_rabbitmq
    env_file:
      - ./env/rabbitmq.env
  spy_jenkins:
    image: nexusnetsoft/jenkins-php:7.3
    container_name: spy_jenkins
    env_file:
      - ./env/jenkins.env
      - ./env/php.env
    links:
      - spy_zed
    depends_on:
      - spy_data
      - spy_php
    volumes:
      - spy_projectdata:/data/shop/development
  spy_loadbalancer:
    image: nginx
    container_name: spy_loadbalancer
    depends_on:
      - spy_zed
      - spy_api
      - spy_swagger
    volumes:
      - ./env/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./env/nginx/loadbalancer.conf:/etc/nginx/conf.d/loadbalancer.conf
    networks:
      default:
        aliases:
          - "www.de.suite.local"
          - "www-test.de.suite.local"
          - "api.de.suite.local"
          - "api-test.de.suite.local"
          - "zed.de.suite.local"
          - "zed-test.de.suite.local"
          - "www.at.suite.local"
          - "www-test.at.suite.local"
          - "zed.at.suite.local"
          - "zed-test.at.suite.local"
          - "api.at.suite.local"
          - "api-test.at.suite.local"
          - "www.us.suite.local"
          - "www-test.us.suite.local"
          - "zed.us.suite.local"
          - "zed-test.us.suite.local"
          - "api.us.suite.local"
          - "api-test.us.suite.local"
          - "api.swagger.suite.local"
  spy_yves:
    image: nginx
    container_name: spy_yves
    volumes:
      - ./env/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./env/nginx/de_yves_spryker.conf:/etc/nginx/conf.d/de_yves_spryker.conf
      - ./env/nginx/de_test_spryker.conf:/etc/nginx/conf.d/de_test_spryker.conf
      - ./env/nginx/at_yves_spryker.conf:/etc/nginx/conf.d/at_yves_spryker.conf
      - ./env/nginx/at_test_spryker.conf:/etc/nginx/conf.d/at_test_spryker.conf
      - ./env/nginx/us_yves_spryker.conf:/etc/nginx/conf.d/us_yves_spryker.conf
      - ./env/nginx/us_test_spryker.conf:/etc/nginx/conf.d/us_test_spryker.conf
      - spy_projectdata:/data/shop/development
    depends_on:
      - spy_php
  spy_api:
    image: nginx
    container_name: spy_api
    volumes:
      - ./env/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./env/nginx/de_api_spryker.conf:/etc/nginx/conf.d/de_api_spryker.conf
      - ./env/nginx/de_test_api_spryker.conf:/etc/nginx/conf.d/de_test_api_spryker.conf
      - ./env/nginx/at_api_spryker.conf:/etc/nginx/conf.d/at_api_spryker.conf
      - ./env/nginx/at_test_api_spryker.conf:/etc/nginx/conf.d/at_test_api_spryker.conf
      - ./env/nginx/us_api_spryker.conf:/etc/nginx/conf.d/us_api_spryker.conf
      - ./env/nginx/us_test_api_spryker.conf:/etc/nginx/conf.d/us_test_api_spryker.conf
      - spy_projectdata:/data/shop/development
    depends_on:
      - spy_php
  spy_zed:
    image: nginx
    container_name: spy_zed
    volumes:
      - ./env/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./env/nginx/de_zed_spryker.conf:/etc/nginx/conf.d/de_zed_spryker.conf
      - ./env/nginx/de_test_zed_spryker.conf:/etc/nginx/conf.d/de_test_zed_spryker.conf
      - ./env/nginx/at_zed_spryker.conf:/etc/nginx/conf.d/at_zed_spryker.conf
      - ./env/nginx/at_test_zed_spryker.conf:/etc/nginx/conf.d/at_test_zed_spryker.conf
      - ./env/nginx/us_zed_spryker.conf:/etc/nginx/conf.d/us_zed_spryker.conf
      - ./env/nginx/us_test_zed_spryker.conf:/etc/nginx/conf.d/us_test_zed_spryker.conf
      - spy_projectdata:/data/shop/development
    depends_on:
      - spy_php
  spy_swagger:
    image: swaggerapi/swagger-ui
    container_name: spy_swagger
    environment:
      API_URL: http://api.swagger.suite.local

volumes:
  spy_projectdata:
    external: true
  spy_elasticdata:
    external: true
  spy_redisdata:
    external: true
  spy_dbdata:
    external: true
